# Generated by Django 3.2.5 on 2021-08-30 17:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoapp', '0002_auto_20210830_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnail_uploaded'),
        ),
        migrations.AddField(
            model_name='videos',
            name='video',
            field=models.FileField(default=None, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
